### ISSUE TITLE
ARM: armips will not allow `mov rX, #0xF1` or greater

### ISSUE THREAD

**Issue by archshift** [Kingcom/armips#84] opened 2017-01-09 06:27 UTC
Attempting to `mov` anything between `0xF1` and `0xFF` is met with "error: Invalid shifted immediate XX".

**Comment by Kingcom** [comment] 2017-01-28 09:27
I couldn't reproduce this. Can you post some sample code that triggers it?

**Comment by archshift** [comment] 2017-01-31 19:14
This did it for me:

```assembly
.nds
.create "foo.bin", 0x0
mov r0, #0xFF
```

**Comment by sp1187** [comment] 2017-01-31 22:57
Your example works correctly for me.
Could you compile/download the latest version and try that one?

**Comment by archshift** [comment] 2017-02-03 07:02
Nope, continue to have the same problem.

For context, I'm on a mac, using `ARMIPS64 Assembler v0.9.0 (Feb  2 2017 22:58:55) by Kingcom`.

**Comment by Z6n4** [comment] 2017-04-21 16:25
I am having the same issue in 0.8.0
My value is 0x1140, and it's saying "Invalid shifted immediate 1160" (trying to add 0x20)

**Comment by Kingcom** [comment] 2017-04-21 16:44
0x1160 cannot be represented as a shifted immediate. If you convert the value to binary, you get  0b1000101100000. Here, you need to remove an _even_ amount of least significant zero bits. This results in 0b100010110, which is 9 bits, while a shifted immediate has to fit into 8 bits.
0x1140 is 0b1000101000000, and thus 0b1000101, which fits into 8 bits.

**Comment by Kingcom** [comment] 2017-07-10 14:56
This is very likely to be the same issue as in #108, so I'm closing it for now. Let me know if the issue persists.

**Closed by Kingcom** 2017-07-10 14:56 UTC
